# --- !Ups

CREATE TABLE "USERS" (
  "ID" BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
  "ROLE" VARCHAR(20) NOT NULL,
  "USERNAME" VARCHAR(100) NOT NULL UNIQUE,
  "PASSWORD" VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
  );

CREATE TABLE "POSTS" (
  "ID" BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
  "AUTHOR_ID" BIGINT NOT NULL UNIQUE,
  "TITLE" VARCHAR(100) NOT NULL,
  "CONTENT" VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT USER_FK FOREIGN KEY (AUTHOR_ID)
  REFERENCES USERS(ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE
  );

INSERT INTO USERS VALUES (1, 'admin', 'testAdmin', '$2a$10$mEl.bADmpqEn3Q7d.6hqjOsgCnX0MQQXSsZ8DfWFKSVe6Xd3f2GyK');

INSERT INTO USERS VALUES (2, 'user', 'testUser', '$2a$10$mEl.bADmpqEn3Q7d.6hqjOsgCnX0MQQXSsZ8DfWFKSVe6Xd3f2GyK');

# --- !Downs

DROP TABLE "POSTS";
DROP TABLE "USERS";
